/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppProvider: (typeof import('./../src/components/common/AppProvider.vue'))['default']
    NAvatar: (typeof import('naive-ui'))['NAvatar']
    NBreadcrumb: (typeof import('naive-ui'))['NBreadcrumb']
    NBreadcrumbItem: (typeof import('naive-ui'))['NBreadcrumbItem']
    NButton: (typeof import('naive-ui'))['NButton']
    NCard: (typeof import('naive-ui'))['NCard']
    NCheckbox: (typeof import('naive-ui'))['NCheckbox']
    NDropdown: (typeof import('naive-ui'))['NDropdown']
    NForm: (typeof import('naive-ui'))['NForm']
    NFormItem: (typeof import('naive-ui'))['NFormItem']
    NGi: (typeof import('naive-ui'))['NGi']
    NGrid: (typeof import('naive-ui'))['NGrid']
    NIcon: (typeof import('naive-ui'))['NIcon']
    NImage: (typeof import('naive-ui'))['NImage']
    NInput: (typeof import('naive-ui'))['NInput']
    NLayout: (typeof import('naive-ui'))['NLayout']
    NLayoutContent: (typeof import('naive-ui'))['NLayoutContent']
    NLayoutHeader: (typeof import('naive-ui'))['NLayoutHeader']
    NLayoutSider: (typeof import('naive-ui'))['NLayoutSider']
    NList: (typeof import('naive-ui'))['NList']
    NListItem: (typeof import('naive-ui'))['NListItem']
    NMenu: (typeof import('naive-ui'))['NMenu']
    NScrollbar: (typeof import('naive-ui'))['NScrollbar']
    NThing: (typeof import('naive-ui'))['NThing']
    PageBlock: (typeof import('./../src/components/block/PageBlock.vue'))['default']
    PageHeader: (typeof import('./../src/components/header/PageHeader.vue'))['default']
    RouterLink: (typeof import('vue-router'))['RouterLink']
    RouterView: (typeof import('vue-router'))['RouterView']
  }
}
